version: 2.1

orbs:
  docker: ledger/docker@volatile

executors:
  sbt-executor:
    docker:
      - image: ledgerhq/jdk8-centos

jobs:
  run_tests:
    executor: sbt-executor
    working_directory: ~/project
    steps:
    - run:
        name: Clean workspace
        command: rm -fr ~/project
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{checksum "build.sbt" }}
        - v1-dependencies-
    - run:
        name: Run unit tests
        command: cat /dev/null | sbt daemon/test
    - save_cache:
        paths:
        - ~/.ivy2
        - ~/.sbt
        key: v1-dependencies--{{checksum "build.sbt" }}

workflows:
  build_test_and_publish:
    jobs:
      - run_tests:
          filters:
            tags:
              only: /.*/
      - docker/build_image:
          requires:
            - run_tests
          filters:
            tags:
              only: /v.*/
      - docker/test_image:
          requires:
            - docker/build_image
          filters:
            tags:
              only: /v.*/
      - docker/publish_image:
          requires:
            - docker/test_image
          filters:
            branches:
              only: master
            tags:
              only: /v.*/
