version: 2.1

orbs:
  docker: ledger/docker@volatile

jobs:
  run_tests:
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: cat /dev/null | sbt daemon/test

workflows:
  build_test_and_publish:
    jobs:
      - run_tests
      - docker/build_image:
          requires:
            - run_tests
          filters:
            tags:
              only: /v.*/
      - docker/test_image:
          requires:
            - docker/build_image
          filters:
            tags:
              only: /v.*/
      - docker/publish_image:
          requires:
            - docker/test_image
          filters:
            branches:
              only: master
            tags:
              only: /v.*/
